# Generated by Django 3.2.8 on 2021-11-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='Maillot_Third.jpeg', null=True, upload_to=''),
        ),
    ]
