
# Generated by Django 3.2.8 on 2021-11-17 21:15

# Generated by Django 3.2.8 on 2025-06-24 15:51


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('nom', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('titre', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('nom', models.CharField(blank=True, max_length=200, null=True)),
                ('added', models.DateField(auto_now_add=True, null=True)),
                ('url', models.FileField(blank=True, upload_to='video/%y')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['added'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('taille', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('poids', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('nom', models.CharField(blank=True, max_length=200, null=True)),
                ('nationalité', models.CharField(blank=True, max_length=200, null=True)),
                ('poste', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('matchs', models.IntegerField(blank=True, default=0, null=True)),
                ('goals', models.IntegerField(blank=True, default=0, null=True)),
                ('assists', models.IntegerField(blank=True, default=0, null=True)),
                ('yellowCard', models.IntegerField(blank=True, default=0, null=True)),
                ('redCard', models.IntegerField(blank=True, default=0, null=True)),
                ('onPenalties', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(blank=True, default=0, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medias',
            fields=[
                ('titre', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('added', models.DateField(auto_now_add=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('Interview', 'Interview'), ('Réactions', 'Réactions'), ('Matchs', 'Matchs')], default='Matchs', max_length=20)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medias', to='vitrine.gallery')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('nom', models.CharField(blank=True, max_length=200, null=True)),
                ('titre', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
