# Generated by Django 3.2.8 on 2021-11-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0002_auto_20211124_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
