# Generated by Django 3.2.8 on 2021-11-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0003_auto_20211124_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='nom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
