# Generated by Django 3.2.8 on 2021-11-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0004_article_nom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
