# Generated by Django 3.2.8 on 2021-11-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0006_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='poids',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='taille',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
