# Generated by Django 3.2.8 on 2021-11-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0007_auto_20211125_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
