# Generated by Django 3.2.8 on 2021-11-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0008_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='onPenalties',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
