# Generated by Django 3.2.8 on 2021-11-29 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0009_player_onpenalties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='match',
            new_name='matchs',
        ),
    ]
