# Generated by Django 3.2.8 on 2021-11-29 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0010_rename_match_player_matchs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='cleanSheets',
        ),
        migrations.RemoveField(
            model_name='player',
            name='debutDeContrat',
        ),
        migrations.RemoveField(
            model_name='player',
            name='finDeContrat',
        ),
        migrations.RemoveField(
            model_name='player',
            name='penaltiesSaves',
        ),
    ]
