# Generated by Django 3.2.8 on 2021-12-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0014_alter_photo_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='nom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
