# Generated by Django 3.2.8 on 2021-12-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0015_photo_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
