# Generated by Django 3.2.8 on 2021-12-02 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vitrine', '0016_gallery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='id',
        ),
        migrations.AddField(
            model_name='photo',
            name='_id',
            field=models.AutoField(default=1, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='vitrine.gallery'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('added', models.DateField(auto_now_add=True, null=True)),
                ('url', embed_video.fields.EmbedVideoField()),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['added'],
            },
        ),
    ]
