# Generated by Django 3.2.8 on 2021-12-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0017_auto_20211202_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='_id',
        ),
        migrations.AddField(
            model_name='photo',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
