# Generated by Django 3.2.8 on 2021-12-02 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0018_auto_20211202_2101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
