# Generated by Django 3.2.8 on 2021-12-02 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0020_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='nom',
            new_name='title',
        ),
    ]
