# Generated by Django 3.2.8 on 2021-12-02 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0021_rename_nom_photo_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
