# Generated by Django 3.2.8 on 2021-12-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0023_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='nom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
