# Generated by Django 3.2.8 on 2021-12-02 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0024_video_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='nom',
        ),
    ]
