# Generated by Django 3.2.8 on 2021-12-02 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0026_auto_20211203_0039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
