# Generated by Django 3.2.8 on 2021-12-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0028_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='upload',
            field=models.FileField(blank=True, upload_to='video/%y'),
        ),
    ]
