# Generated by Django 3.2.8 on 2021-12-03 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0029_video_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
    ]
