# Generated by Django 3.2.8 on 2021-12-03 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0030_remove_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='upload',
            new_name='url',
        ),
    ]
