# Generated by Django 3.2.8 on 2021-12-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0031_rename_upload_video_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['added']},
        ),
        migrations.AddField(
            model_name='photo',
            name='added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
