# Generated by Django 3.2.8 on 2021-12-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0033_auto_20211203_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
