# Generated by Django 3.2.8 on 2021-12-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0034_media_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='categorie',
            field=models.CharField(blank=True, choices=[('Interview', 'Interview'), ('Réactions', 'Réactions'), ('Matchs', 'Matchs')], default='Matchs', max_length=20),
        ),
    ]
