# Generated by Django 3.2.8 on 2025-12-17 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0002_video'),
        ('vitrine', '0035_media_categorie'),
    ]

    operations = [
    ]
